---
version: "3.8"
services:
 app:
   image: wikipedialibrary/externallinks:app_branch_${IMAGE_VERSION}
   build:
     context: .
     target: externallinks
   env_file:
     - '.env'
   depends_on:
     - db
   ports:
     - "8000:8000"
   volumes:
     - ./:/app
 db:
   image: mysql:5.7
   env_file:
     - '.env'
   ports:
     - "3306:3306"
   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
   healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-plinks"]
     timeout: 20s
     interval: 10s
     retries: 10
 nginx:
   image: nginx
   volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
     - ./static:/app/static
   ports:
     - "80:80"
   depends_on:
     - app
 eventstream:
   image: wikipedialibrary/eventstream:eventstream_branch_${IMAGE_VERSION}
   build:
     context: .
     target: eventstream
   depends_on:
     - db
   env_file:
     - '.env'
   volumes:
     - ./:/app
 cache:
   image: memcached
   ports:
    - "11211:11211"
   entrypoint:
     - memcached
   depends_on:
     - app
