---
version: "3.8"
services:
 app:
   image: wikipedialibrary/externallinks:app_branch_staging
   build:
     context: .
     target: externallinks
   env_file:
     - '.env'
   depends_on:
     - 'migrate'
   ports:
     - "8000:8000"
   volumes:
     - ./:/app
