name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - staging

  # Run tests for any PRs.
  pull_request:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Start Image
        run: |
          cp template.env .env
          docker-compose up -d --build
      - name: Check Running Containers
        run: |
          docker-compose ps -a
      - name: Run tests
        run: |
          docker-compose exec -T app /django_wait_for_db.sh python django_wait_for_migrations.py test

# Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push externallinks image
        run: |
          IMAGE_ID=wikipedialibrary/externallinks

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker tag $IMAGE_ID:latest $IMAGE_ID:branch_$VERSION
          docker tag $IMAGE_ID:latest $IMAGE_ID:commit_${GITHUB_SHA::8}
          docker push $IMAGE_ID:branch_$VERSION
          docker push $IMAGE_ID:commit_${GITHUB_SHA::8}

      - name: Push eventstream image
        run: |
          IMAGE_ID=wikipedialibrary/eventstream

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker tag $IMAGE_ID:latest $IMAGE_ID:branch_$VERSION
          docker tag $IMAGE_ID:latest $IMAGE_ID:commit_${GITHUB_SHA::8}
          docker push $IMAGE_ID:branch_$VERSION
          docker push $IMAGE_ID:commit_${GITHUB_SHA::8}
