name: Test

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Python Django Coverage GitHub Action
      uses: dc740/django-coveragepy-github-action@0.9
      with:
        # Application
        django-app: 'externallinks'
        # Minimum allowed code coverage
        minimum-coverage: 50
